import React, { useState, useEffect } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";

import { Popover, PopoverContent, PopoverTrigger } from "@/components/ui/popover";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Switch } from "@/components/ui/switch";
import { Badge } from "@/components/ui/badge";
import { X, Save, Target as TargetIcon, Check, ChevronsUpDown, Infinity as InfinityIcon } from "lucide-react"; // Adicionado Check, ChevronsUpDown
import { Command, CommandEmpty, CommandGroup, CommandInput, CommandItem, CommandList } from "@/components/ui/command";
import { format, parseISO, startOfMonth, endOfMonth } from "date-fns";
import { getTagPath, isLeafTag, MONTH_NAMES_PT, getYearOptions } from "@/utils";

const budgetPeriods = [
  { value: "monthly", label: "Mensal" },
  { value: "weekly", label: "Semanal" },
  { value: "yearly", label: "Anual" },
  // { value: "custom", label: "Personalizado" } // Adicionar depois se necessário
];

export default function BudgetForm({ budget, tags, onSave, onCancel }) {
  // Um orçamento sem end_date (ou com end_date ainda no futuro) está vigente: só se encerra
  // quando um novo orçamento é lançado para a mesma tag (fecha o anterior automaticamente) ou
  // quando é formalmente encerrado. Editar um orçamento já encerrado permite corrigir as duas datas.
  const todayStr = format(new Date(), "yyyy-MM-dd");
  const isEditingClosedBudget = !!(budget && budget.end_date && budget.end_date < todayStr);
  const initialStartDate = budget?.start_date ? parseISO(budget.start_date) : startOfMonth(new Date());

  const [formData, setFormData] = useState({
    tag_id: budget?.tag_id || (tags.length > 0 ? tags[0].id : ""),
    amount: budget?.amount || 0,
    period: budget?.period || "monthly",
    start_date: format(initialStartDate, "yyyy-MM-dd"),
    end_date: budget?.end_date || null,
    is_active: budget?.is_active !== false
  });
  const [isLoading, setIsLoading] = useState(false);
  const [tagPopoverOpen, setTagPopoverOpen] = useState(false);
  const [tagSearchValue, setTagSearchValue] = useState("");


  useEffect(() => {
    const startDate = budget?.start_date ? parseISO(budget.start_date) : startOfMonth(new Date());
    const initialTagId = budget?.tag_id || (tags.length > 0 ? tags[0].id : "");
    setFormData({
      tag_id: initialTagId,
      amount: budget?.amount || 0,
      period: budget?.period || "monthly",
      start_date: format(startDate, "yyyy-MM-dd"),
      end_date: budget?.end_date || null,
      is_active: budget?.is_active !== false
    });

    const currentTag = tags.find(t => t.id === initialTagId);
    setTagSearchValue(currentTag ? getTagPath(currentTag.id, tags) : "");

  }, [budget, tags]);

  const handleSubmit = async (e) => {
    e.preventDefault();
    setIsLoading(true);
    try {
      // Gerar nome automaticamente baseado na tag e período
      const selectedTag = tags.find(t => t.id === formData.tag_id);
      const tagName = selectedTag ? selectedTag.name : 'Tag';

      const periodLabel = budgetPeriods.find(p => p.value === formData.period)?.label || 'Período';
      const autoGeneratedName = `Orçamento ${tagName} - ${periodLabel}`;

      await onSave({
        ...formData,
        name: autoGeneratedName
      });
    } catch (error) {
      console.error("Erro ao salvar orçamento:", error);
    }
    setIsLoading(false);
  };

  const handleInputChange = (field, value) => {
    setFormData(prev => ({
      ...prev,
      [field]: value
    }));
  };

  const handleStartMonthYearChange = (month, year) => {
    handleInputChange("start_date", format(new Date(year, month, 1), "yyyy-MM-dd"));
  };

  const handleEndMonthYearChange = (month, year) => {
    handleInputChange("end_date", format(endOfMonth(new Date(year, month, 1)), "yyyy-MM-dd"));
  };

  const leafTags = tags.filter(tag => isLeafTag(tag, tags));
  const leafTagsWithPath = leafTags.map(tag => ({ ...tag, _displayPath: getTagPath(tag.id, tags) }));

  const filteredTags = leafTagsWithPath.filter(tag =>
    tag._displayPath.toLowerCase().includes(tagSearchValue.toLowerCase())
  );

  const selectedTag = leafTagsWithPath.find(t => t.id === formData.tag_id)
    || tags.find(t => t.id === formData.tag_id);

  return (
    <Card className="shadow-2xl border-0 max-h-[90vh] flex flex-col rounded-2xl bg-white">
      <CardHeader className="bg-gradient-to-r from-orange-50 to-orange-100 border-b sticky top-0 z-10">
        <div className="flex items-center justify-between">
          <CardTitle className="flex items-center gap-3">
            <div className="p-2 bg-orange-100 rounded-lg">
              <TargetIcon className="w-6 h-6 text-orange-600" />
            </div>
            {budget ? "Editar Orçamento" : "Novo Orçamento"}
          </CardTitle>
          <Button variant="ghost" size="icon" onClick={onCancel}>
            <X className="w-5 h-5" />
          </Button>
        </div>
      </CardHeader>

      <CardContent className="p-8 overflow-y-auto flex-grow">
        <form onSubmit={handleSubmit} className="space-y-6">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div className="space-y-2">
              <Label htmlFor="amount" className="text-sm font-medium text-gray-700">
                Valor Planejado *
              </Label>
              <div className="relative">
                <span className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-500 font-medium">R$</span>
                <Input
                  id="amount"
                  type="number"
                  step="0.01"
                  value={formData.amount}
                  onChange={(e) => handleInputChange("amount", parseFloat(e.target.value) || 0)}
                  placeholder="0,00"
                  required
                  className="h-12 pl-10 border-gray-200 focus:border-orange-500 focus:ring-orange-500 rounded-xl transition-all shadow-sm"
                />
              </div>
            </div>

            <div className="space-y-2">
              <Label htmlFor="tag_id_combobox" className="text-sm font-medium">
                Tag Associada *
              </Label>
              <Popover open={tagPopoverOpen} onOpenChange={setTagPopoverOpen}>
                <PopoverTrigger asChild>
                  <Button
                    variant="outline"
                    role="combobox"
                    aria-expanded={tagPopoverOpen}
                    className="w-full justify-between h-12 font-normal border-gray-200 hover:border-orange-500 hover:bg-orange-50 rounded-xl transition-all shadow-sm"
                    id="tag_id_combobox"
                  >
                    {selectedTag ? selectedTag._displayPath : "Selecione uma tag..."}
                    <ChevronsUpDown className="ml-2 h-4 w-4 shrink-0 opacity-50" />
                  </Button>
                </PopoverTrigger>
                <PopoverContent className="w-[--radix-popover-trigger-width] p-0">
                  <Command>
                    <CommandInput
                      placeholder="Buscar tag..."
                      value={tagSearchValue}
                      onValueChange={setTagSearchValue}
                    />
                    <CommandList>
                      <CommandEmpty>Nenhuma tag encontrada.</CommandEmpty>
                      <CommandGroup>
                        {filteredTags.map((tag) => (
                          <CommandItem
                            key={tag.id}
                            value={tag._displayPath}
                            onSelect={(currentValue) => {
                              const currentSelectedTag = leafTagsWithPath.find(t => t._displayPath.toLowerCase() === currentValue.toLowerCase());
                              handleInputChange("tag_id", currentSelectedTag ? currentSelectedTag.id : "");
                              setTagSearchValue(currentSelectedTag ? currentSelectedTag._displayPath : "");
                              setTagPopoverOpen(false);
                            }}
                          >
                            <Check
                              className={`mr-2 h-4 w-4 ${formData.tag_id === tag.id ? "opacity-100" : "opacity-0"}`}
                            />
                            <span className="text-xs text-outline mr-1 font-mono">{tag._displayPath}</span>
                          </CommandItem>
                        ))}
                      </CommandGroup>
                    </CommandList>
                  </Command>
                </PopoverContent>
              </Popover>
            </div>
          </div>

          {selectedTag && selectedTag.parent_tag_id && (
            <div className="p-3 bg-blue-50 border border-blue-200 rounded-lg">
              <p className="text-sm text-blue-700">
                <span className="font-semibold">Categoria:</span> {getTagPath(selectedTag.parent_tag_id, tags)}
              </p>
              <p className="text-xs text-blue-600 mt-1">
                O orçamento total da categoria será a soma dos orçamentos de todas as subcategorias.
              </p>
            </div>
          )}

          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div className="space-y-2">
              <Label className="text-sm font-medium text-gray-700">
                {isEditingClosedBudget ? "Início da Vigência *" : "Vigente a partir de *"}
              </Label>
              <div className="flex gap-2">
                <Select
                  value={String(parseISO(formData.start_date).getMonth())}
                  onValueChange={(v) => handleStartMonthYearChange(Number(v), parseISO(formData.start_date).getFullYear())}
                >
                  <SelectTrigger className="h-12 flex-[3] border-gray-200 hover:border-orange-500 rounded-xl transition-all shadow-sm">
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    {MONTH_NAMES_PT.map((name, idx) => (
                      <SelectItem key={idx} value={String(idx)}>{name}</SelectItem>
                    ))}
                  </SelectContent>
                </Select>
                <Select
                  value={String(parseISO(formData.start_date).getFullYear())}
                  onValueChange={(v) => handleStartMonthYearChange(parseISO(formData.start_date).getMonth(), Number(v))}
                >
                  <SelectTrigger className="h-12 flex-[2] border-gray-200 hover:border-orange-500 rounded-xl transition-all shadow-sm">
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    {getYearOptions(parseISO(formData.start_date).getFullYear()).map(y => (
                      <SelectItem key={y} value={String(y)}>{y}</SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>
            </div>

            {isEditingClosedBudget ? (
              <div className="space-y-2">
                <Label className="text-sm font-medium text-gray-700">
                  Término da Vigência *
                </Label>
                <div className="flex gap-2">
                  <Select
                    value={String(parseISO(formData.end_date).getMonth())}
                    onValueChange={(v) => handleEndMonthYearChange(Number(v), parseISO(formData.end_date).getFullYear())}
                  >
                    <SelectTrigger className="h-12 flex-[3] border-gray-200 hover:border-orange-500 rounded-xl transition-all shadow-sm">
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent>
                      {MONTH_NAMES_PT.map((name, idx) => (
                        <SelectItem key={idx} value={String(idx)}>{name}</SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                  <Select
                    value={String(parseISO(formData.end_date).getFullYear())}
                    onValueChange={(v) => handleEndMonthYearChange(parseISO(formData.end_date).getMonth(), Number(v))}
                  >
                    <SelectTrigger className="h-12 flex-[2] border-gray-200 hover:border-orange-500 rounded-xl transition-all shadow-sm">
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent>
                      {getYearOptions(parseISO(formData.end_date).getFullYear()).map(y => (
                        <SelectItem key={y} value={String(y)}>{y}</SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </div>
              </div>
            ) : (
              <div className="flex items-center gap-2 p-3 bg-gray-50/80 rounded-xl border border-gray-100">
                <InfinityIcon className="w-4 h-4 text-orange-500 shrink-0" />
                <p className="text-xs text-gray-500">
                  Sem data de término: este orçamento continua valendo até que um novo seja lançado para a mesma tag, ou até ser encerrado manualmente.
                </p>
              </div>
            )}
          </div>

          {isEditingClosedBudget && (
            <div className="flex items-center gap-2 -mt-2">
              <Badge variant="outline" className="border-gray-300 text-gray-500">Orçamento encerrado</Badge>
              <p className="text-xs text-gray-500">Você pode corrigir as datas deste orçamento histórico, se necessário.</p>
            </div>
          )}

          <div className="flex items-center justify-between p-4 bg-gray-50/80 rounded-xl border border-gray-100 hover:border-gray-200 transition-colors">
            <div className="space-y-0.5">
              <Label htmlFor="is_active" className="text-base font-medium text-gray-900 cursor-pointer">
                Orçamento Ativo
              </Label>
              <p className="text-sm text-gray-500">
                Orçamentos inativos ficam ocultos no painel.
              </p>
            </div>
            <Switch
              id="is_active"
              checked={formData.is_active}
              onCheckedChange={(checked) => handleInputChange("is_active", checked)}
              className="data-[state=checked]:bg-orange-500 data-[state=unchecked]:bg-gray-200"
            />
          </div>

          <div className="flex justify-end gap-4 pt-6 border-t sticky bottom-0 bg-white py-6 z-10">
            <Button
              type="button"
              variant="ghost"
              onClick={onCancel}
              disabled={isLoading}
              className="h-12 px-8 text-gray-600 hover:text-gray-900 hover:bg-gray-100 rounded-xl"
            >
              Cancelar
            </Button>
            <Button
              type="submit"
              disabled={isLoading || !formData.tag_id}
              className="h-12 px-8 bg-orange-600 hover:bg-orange-700 text-white shadow-lg shadow-orange-200 rounded-xl transition-all hover:scale-[1.02] active:scale-[0.98]"
            >
              {isLoading ? (
                <>
                  <div className="w-4 h-4 border-2 border-white border-t-transparent rounded-full animate-spin mr-2" />
                  Salvando...
                </>
              ) : (
                <>
                  <Save className="w-4 h-4 mr-2" />
                  {budget ? "Atualizar" : "Criar"} Orçamento
                </>
              )}
            </Button>
          </div>
        </form>
      </CardContent>
    </Card>
  );
}
